name: crs_ahmadi
description: "CRS - Complaint Registration System"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  page_transition: ^2.2.1
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  flutter_spinkit: ^5.2.1
  image_cropper: ^9.0.0
  http: ^1.3.0
  http_parser: ^4.1.2
  file_picker: ^9.2.0
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "favicon.png"
    background_color: "#00000000"
    theme_color: "#00000000"
#  windows:
#    generate: true
#    image_path: "path/to/image.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "path/to/image.png"
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
#    - family: Vazir
#      fonts:
#        - asset: assets/fonts/Vazir.ttf
    - family: Shabnam
      fonts:
        - asset: assets/fonts/Shabnam.ttf
          weight: 400